name: measuresnap
description: Measure anything using reference objects in photos
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core functionality
  camera: ^0.10.5
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # ML and image processing (Optional - comment out if causing issues)
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_image_labeling: ^0.10.0
  # opencv_dart: ^0.0.5  # Comment this out - often causes build issues
  
  # State management
  provider: ^6.1.0
  
  # Local storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # UI enhancements
  # flutter_ruler_picker: ^1.0.0  # Comment out - not essential
  photo_view: ^0.14.0
  
  # Export and sharing
  pdf: ^3.10.7
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  
  # Backup functionality
  file_picker: ^6.1.1
  archive: ^3.4.9
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.18.1
  collection: ^1.18.0
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/reference_guides/
  
  # Comment out fonts if you don't have them
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Montserrat-Bold.ttf
  #         weight: 700